# =============================================================================
# Forseti Cloud Build Configuration
# Builds and deploys API and Web services to Google Cloud Run
# =============================================================================

steps:
  # -----------------------------------------------------------------------------
  # Step 1: Build API Docker image
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:latest'
      - '-f'
      - 'forseti-app/docker/api/Dockerfile'
      - 'forseti-app'
    id: 'build-api'

  # -----------------------------------------------------------------------------
  # Step 2: Build Web Docker image
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:latest'
      - '-f'
      - 'forseti-app/docker/web/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://forseti-api-${_CLOUD_RUN_SUFFIX}.run.app'
      - 'forseti-app'
    id: 'build-web'

  # -----------------------------------------------------------------------------
  # Step 3: Push API image to Artifact Registry
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:$COMMIT_SHA'
    id: 'push-api'
    waitFor: ['build-api']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:latest'
    waitFor: ['push-api']

  # -----------------------------------------------------------------------------
  # Step 4: Push Web image to Artifact Registry
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:$COMMIT_SHA'
    id: 'push-web'
    waitFor: ['build-web']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:latest'
    waitFor: ['push-web']

  # -----------------------------------------------------------------------------
  # Step 5: Deploy API to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'forseti-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:forseti-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=postgresql://postgres:ForsetiDB2025!@/forseti?host=/cloudsql/$PROJECT_ID:us-central1:forseti-db,JWT_SECRET=${_JWT_SECRET},ALLOWED_ORIGINS=https://forseti-web-${_CLOUD_RUN_SUFFIX}.run.app'
    id: 'deploy-api'
    waitFor: ['push-api']

  # -----------------------------------------------------------------------------
  # Step 6: Deploy Web to Cloud Run
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'forseti-web'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-web'
    waitFor: ['push-web', 'deploy-api']

substitutions:
  _JWT_SECRET: 'forseti-jwt-secret-production-2025'
  _CLOUD_RUN_SUFFIX: '173360556184'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-api:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/forseti-repo/forseti-web:latest'

timeout: '1800s'
